spring:
  ai:
    spark:
      api-key: ${api-key}
      base-url: https://spark-api-open.xf-yun.com/v1/chat/completions
      chat:
        options:
          model: lite


# 修改日志级别
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
server:
  port: 8088